/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) standard_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[20] = 
  {19, 1, 0, 16, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 18};

static const casadi_real casadi_zeros[13] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* standard_expl_vde_adj:(i0[13],i1[13],i2[6],i3[0])->(o0[19x1,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, w01, *w02=w+9, w03, w04, w05, w06, w07, w08, *w09=w+18, *w10=w+22;
  casadi_real *w11=w+26, *w12=w+30, *w13=w+34, w15, w16, w17, *w18=w+66, *w19=w+75, *w20=w+78, *w21=w+81, *w22=w+90, *w23=w+93;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, *w39=w+111, *w40=w+114;
  const casadi_real *cs, *ct, *wr02, *wr09, *wr14;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w00, 4);
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w02);
  /* #3: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #4: @4 = (-@3) */
  w04 = (- w03 );
  /* #5: @5 = @2[1] */
  for (rr=(&w05), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #6: @6 = (-@5) */
  w06 = (- w05 );
  /* #7: @7 = @2[2] */
  for (rr=(&w07), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #8: @8 = (-@7) */
  w08 = (- w07 );
  /* #9: @9 = horzcat(@1, @4, @6, @8) */
  rr=w09;
  *rr++ = w01;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w08;
  /* #10: @9 = @9' */
  /* #11: @10 = horzcat(@3, @1, @7, @6) */
  rr=w10;
  *rr++ = w03;
  *rr++ = w01;
  *rr++ = w07;
  *rr++ = w06;
  /* #12: @10 = @10' */
  /* #13: @11 = horzcat(@5, @8, @1, @3) */
  rr=w11;
  *rr++ = w05;
  *rr++ = w08;
  *rr++ = w01;
  *rr++ = w03;
  /* #14: @11 = @11' */
  /* #15: @12 = horzcat(@7, @5, @4, @1) */
  rr=w12;
  *rr++ = w07;
  *rr++ = w05;
  *rr++ = w04;
  *rr++ = w01;
  /* #16: @12 = @12' */
  /* #17: @13 = horzcat(@9, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w09; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #18: @4 = 0.5 */
  w04 = 5.0000000000000000e-01;
  /* #19: @14 = input[1][0] */
  wr14 = arg[1] ? arg[1] : casadi_zeros;
  /* #20: {@2, @9, @1, @8, @6, @15, @16, @17} = vertsplit(@14) */
  wr02 = wr14;
  wr09 = wr14+3;
  w01 = wr14[7];
  w08 = wr14[8];
  w06 = wr14[9];
  w15 = wr14[10];
  w16 = wr14[11];
  w17 = wr14[12];
  /* #21: @9 = (@4*@9) */
  for (i=0, rr=w09, cs=wr09; i<4; ++i) (*rr++)  = (w04*(*cs++));
  /* #22: @0 = mac(@13,@9,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w13+j, ct=w09+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #23: @10 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w10);
  /* #24: @4 = @10[1] */
  for (rr=(&w04), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #25: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #26: @19 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w19);
  /* #27: @20 = @19' */
  casadi_copy(w19, 3, w20);
  /* #28: @18 = mac(@2,@20,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr02+j, ct=w20+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #29: @21 = @18' */
  for (i=0, rr=w21, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #30: {@20, @22, @23} = horzsplit(@21) */
  casadi_copy(w21, 3, w20);
  casadi_copy(w21+3, 3, w22);
  casadi_copy(w21+6, 3, w23);
  /* #31: @23 = @23' */
  /* #32: {@24, @25, @26} = horzsplit(@23) */
  w24 = w23[0];
  w25 = w23[1];
  w26 = w23[2];
  /* #33: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #34: @27 = (@4*@25) */
  w27  = (w04*w25);
  /* #35: @28 = @10[2] */
  for (rr=(&w28), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #36: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #37: @29 = (@28*@24) */
  w29  = (w28*w24);
  /* #38: @27 = (@27-@29) */
  w27 -= w29;
  /* #39: @22 = @22' */
  /* #40: {@29, @30, @31} = horzsplit(@22) */
  w29 = w22[0];
  w30 = w22[1];
  w31 = w22[2];
  /* #41: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #42: @32 = (@4*@31) */
  w32  = (w04*w31);
  /* #43: @27 = (@27-@32) */
  w27 -= w32;
  /* #44: @32 = @10[3] */
  for (rr=(&w32), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #45: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #46: @33 = (@32*@29) */
  w33  = (w32*w29);
  /* #47: @27 = (@27+@33) */
  w27 += w33;
  /* #48: @20 = @20' */
  /* #49: {@33, @34, @35} = horzsplit(@20) */
  w33 = w20[0];
  w34 = w20[1];
  w35 = w20[2];
  /* #50: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #51: @36 = (@28*@35) */
  w36  = (w28*w35);
  /* #52: @27 = (@27+@36) */
  w27 += w36;
  /* #53: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #54: @36 = (@32*@34) */
  w36  = (w32*w34);
  /* #55: @27 = (@27-@36) */
  w27 -= w36;
  /* #56: (@0[0] += @27) */
  for (rr=w00+0, cs=(&w27); rr!=w00+1; rr+=1) *rr += *cs++;
  /* #57: @27 = (2.*@4) */
  w27 = (2.* w04 );
  /* #58: @26 = (-@26) */
  w26 = (- w26 );
  /* #59: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #60: @36 = (@27*@26) */
  w36  = (w27*w26);
  /* #61: @37 = @10[0] */
  for (rr=(&w37), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #62: @38 = (@37*@25) */
  w38  = (w37*w25);
  /* #63: @36 = (@36+@38) */
  w36 += w38;
  /* #64: @38 = (@32*@24) */
  w38  = (w32*w24);
  /* #65: @36 = (@36+@38) */
  w36 += w38;
  /* #66: @38 = (@37*@31) */
  w38  = (w37*w31);
  /* #67: @36 = (@36-@38) */
  w36 -= w38;
  /* #68: @30 = (-@30) */
  w30 = (- w30 );
  /* #69: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #70: @27 = (@27*@30) */
  w27 *= w30;
  /* #71: @36 = (@36+@27) */
  w36 += w27;
  /* #72: @27 = (@28*@29) */
  w27  = (w28*w29);
  /* #73: @36 = (@36+@27) */
  w36 += w27;
  /* #74: @27 = (@32*@35) */
  w27  = (w32*w35);
  /* #75: @36 = (@36+@27) */
  w36 += w27;
  /* #76: @27 = (@28*@34) */
  w27  = (w28*w34);
  /* #77: @36 = (@36+@27) */
  w36 += w27;
  /* #78: (@0[1] += @36) */
  for (rr=w00+1, cs=(&w36); rr!=w00+2; rr+=1) *rr += *cs++;
  /* #79: @36 = (@28*@25) */
  w36  = (w28*w25);
  /* #80: @27 = (@4*@24) */
  w27  = (w04*w24);
  /* #81: @36 = (@36+@27) */
  w36 += w27;
  /* #82: @27 = (@28*@31) */
  w27  = (w28*w31);
  /* #83: @36 = (@36+@27) */
  w36 += w27;
  /* #84: @27 = (2.*@32) */
  w27 = (2.* w32 );
  /* #85: @30 = (@27*@30) */
  w30  = (w27*w30);
  /* #86: @36 = (@36+@30) */
  w36 += w30;
  /* #87: @30 = (@37*@29) */
  w30  = (w37*w29);
  /* #88: @36 = (@36+@30) */
  w36 += w30;
  /* #89: @30 = (@4*@35) */
  w30  = (w04*w35);
  /* #90: @36 = (@36+@30) */
  w36 += w30;
  /* #91: @30 = (@37*@34) */
  w30  = (w37*w34);
  /* #92: @36 = (@36-@30) */
  w36 -= w30;
  /* #93: @33 = (-@33) */
  w33 = (- w33 );
  /* #94: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #95: @27 = (@27*@33) */
  w27 *= w33;
  /* #96: @36 = (@36+@27) */
  w36 += w27;
  /* #97: (@0[3] += @36) */
  for (rr=w00+3, cs=(&w36); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #98: @36 = (2.*@28) */
  w36 = (2.* w28 );
  /* #99: @26 = (@36*@26) */
  w26  = (w36*w26);
  /* #100: @25 = (@32*@25) */
  w25  = (w32*w25);
  /* #101: @26 = (@26+@25) */
  w26 += w25;
  /* #102: @24 = (@37*@24) */
  w24  = (w37*w24);
  /* #103: @26 = (@26-@24) */
  w26 -= w24;
  /* #104: @31 = (@32*@31) */
  w31  = (w32*w31);
  /* #105: @26 = (@26+@31) */
  w26 += w31;
  /* #106: @29 = (@4*@29) */
  w29  = (w04*w29);
  /* #107: @26 = (@26+@29) */
  w26 += w29;
  /* #108: @35 = (@37*@35) */
  w35  = (w37*w35);
  /* #109: @26 = (@26+@35) */
  w26 += w35;
  /* #110: @34 = (@4*@34) */
  w34  = (w04*w34);
  /* #111: @26 = (@26+@34) */
  w26 += w34;
  /* #112: @36 = (@36*@33) */
  w36 *= w33;
  /* #113: @26 = (@26+@36) */
  w26 += w36;
  /* #114: (@0[2] += @26) */
  for (rr=w00+2, cs=(&w26); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #115: output[0][0] = @0 */
  casadi_copy(w00, 4, res[0]);
  /* #116: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #117: @26 = 3135 */
  w26 = 3135.;
  /* #118: @36 = @19[2] */
  for (rr=(&w36), cs=w19+2; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #119: @33 = fabs(@36) */
  w33 = casadi_fabs( w36 );
  /* #120: @33 = (@26*@33) */
  w33  = (w26*w33);
  /* #121: @34 = 0.00021645 */
  w34 = 2.1645021645021645e-04;
  /* #122: @6 = (@34*@6) */
  w06  = (w34*w06);
  /* #123: @33 = (@33*@6) */
  w33 *= w06;
  /* #124: @33 = (-@33) */
  w33 = (- w33 );
  /* #125: @22 = @20; (@22[2] += @33) */
  casadi_copy(w20, 3, w22);
  for (rr=w22+2, cs=(&w33); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #126: @33 = sign(@36) */
  w33 = casadi_sign( w36 );
  /* #127: @36 = (@36*@6) */
  w36 *= w06;
  /* #128: @26 = (@26*@36) */
  w26 *= w36;
  /* #129: @33 = (@33*@26) */
  w33 *= w26;
  /* #130: @33 = (-@33) */
  w33 = (- w33 );
  /* #131: (@22[2] += @33) */
  for (rr=w22+2, cs=(&w33); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #132: @33 = 4042 */
  w33 = 4042.;
  /* #133: @26 = @19[1] */
  for (rr=(&w26), cs=w19+1; cs!=w19+2; cs+=1) *rr++ = *cs;
  /* #134: @36 = fabs(@26) */
  w36 = casadi_fabs( w26 );
  /* #135: @36 = (@33*@36) */
  w36  = (w33*w36);
  /* #136: @8 = (@34*@8) */
  w08  = (w34*w08);
  /* #137: @36 = (@36*@8) */
  w36 *= w08;
  /* #138: @36 = (-@36) */
  w36 = (- w36 );
  /* #139: (@22[1] += @36) */
  for (rr=w22+1, cs=(&w36); rr!=w22+2; rr+=1) *rr += *cs++;
  /* #140: @36 = sign(@26) */
  w36 = casadi_sign( w26 );
  /* #141: @26 = (@26*@8) */
  w26 *= w08;
  /* #142: @33 = (@33*@26) */
  w33 *= w26;
  /* #143: @36 = (@36*@33) */
  w36 *= w33;
  /* #144: @36 = (-@36) */
  w36 = (- w36 );
  /* #145: (@22[1] += @36) */
  for (rr=w22+1, cs=(&w36); rr!=w22+2; rr+=1) *rr += *cs++;
  /* #146: @36 = 2327 */
  w36 = 2327.;
  /* #147: @33 = @19[0] */
  for (rr=(&w33), cs=w19+0; cs!=w19+1; cs+=1) *rr++ = *cs;
  /* #148: @26 = fabs(@33) */
  w26 = casadi_fabs( w33 );
  /* #149: @26 = (@36*@26) */
  w26  = (w36*w26);
  /* #150: @34 = (@34*@1) */
  w34 *= w01;
  /* #151: @26 = (@26*@34) */
  w26 *= w34;
  /* #152: @26 = (-@26) */
  w26 = (- w26 );
  /* #153: (@22[0] += @26) */
  for (rr=w22+0, cs=(&w26); rr!=w22+1; rr+=1) *rr += *cs++;
  /* #154: @26 = sign(@33) */
  w26 = casadi_sign( w33 );
  /* #155: @33 = (@33*@34) */
  w33 *= w34;
  /* #156: @36 = (@36*@33) */
  w36 *= w33;
  /* #157: @26 = (@26*@36) */
  w26 *= w36;
  /* #158: @26 = (-@26) */
  w26 = (- w26 );
  /* #159: (@22[0] += @26) */
  for (rr=w22+0, cs=(&w26); rr!=w22+1; rr+=1) *rr += *cs++;
  /* #160: @26 = 1 */
  w26 = 1.;
  /* #161: @36 = sq(@28) */
  w36 = casadi_sq( w28 );
  /* #162: @33 = sq(@32) */
  w33 = casadi_sq( w32 );
  /* #163: @1 = (@36+@33) */
  w01  = (w36+w33);
  /* #164: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #165: @1 = (@26-@1) */
  w01  = (w26-w01);
  /* #166: @35 = (@4*@28) */
  w35  = (w04*w28);
  /* #167: @29 = (@37*@32) */
  w29  = (w37*w32);
  /* #168: @31 = (@35-@29) */
  w31  = (w35-w29);
  /* #169: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #170: @24 = (@4*@32) */
  w24  = (w04*w32);
  /* #171: @25 = (@37*@28) */
  w25  = (w37*w28);
  /* #172: @27 = (@24+@25) */
  w27  = (w24+w25);
  /* #173: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #174: @19 = horzcat(@1, @31, @27) */
  rr=w19;
  *rr++ = w01;
  *rr++ = w31;
  *rr++ = w27;
  /* #175: @19 = @19' */
  /* #176: @35 = (@35+@29) */
  w35 += w29;
  /* #177: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #178: @29 = sq(@4) */
  w29 = casadi_sq( w04 );
  /* #179: @33 = (@29+@33) */
  w33  = (w29+w33);
  /* #180: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #181: @33 = (@26-@33) */
  w33  = (w26-w33);
  /* #182: @28 = (@28*@32) */
  w28 *= w32;
  /* #183: @37 = (@37*@4) */
  w37 *= w04;
  /* #184: @4 = (@28-@37) */
  w04  = (w28-w37);
  /* #185: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #186: @23 = horzcat(@35, @33, @4) */
  rr=w23;
  *rr++ = w35;
  *rr++ = w33;
  *rr++ = w04;
  /* #187: @23 = @23' */
  /* #188: @24 = (@24-@25) */
  w24 -= w25;
  /* #189: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #190: @28 = (@28+@37) */
  w28 += w37;
  /* #191: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #192: @29 = (@29+@36) */
  w29 += w36;
  /* #193: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #194: @26 = (@26-@29) */
  w26 -= w29;
  /* #195: @39 = horzcat(@24, @28, @26) */
  rr=w39;
  *rr++ = w24;
  *rr++ = w28;
  *rr++ = w26;
  /* #196: @39 = @39' */
  /* #197: @21 = horzcat(@19, @23, @39) */
  rr=w21;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<3; ++i) *rr++ = *cs++;
  /* #198: @19 = mac(@21,@2,@20) */
  casadi_copy(w20, 3, w19);
  for (i=0, rr=w19; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=wr02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #199: @22 = (@22+@19) */
  for (i=0, rr=w22, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #200: output[0][1] = @22 */
  if (res[0]) casadi_copy(w22, 3, res[0]+4);
  /* #201: @24 = 11000 */
  w24 = 11000.;
  /* #202: @28 = fabs(@7) */
  w28 = casadi_fabs( w07 );
  /* #203: @28 = (@24*@28) */
  w28  = (w24*w28);
  /* #204: @26 = 0.000179147 */
  w26 = 1.7914725904693657e-04;
  /* #205: @26 = (@26*@17) */
  w26 *= w17;
  /* #206: @28 = (@28*@26) */
  w28 *= w26;
  /* #207: @28 = (-@28) */
  w28 = (- w28 );
  /* #208: (@20[2] += @28) */
  for (rr=w20+2, cs=(&w28); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #209: @28 = sign(@7) */
  w28 = casadi_sign( w07 );
  /* #210: @7 = (@7*@26) */
  w07 *= w26;
  /* #211: @24 = (@24*@7) */
  w24 *= w07;
  /* #212: @28 = (@28*@24) */
  w28 *= w24;
  /* #213: @28 = (-@28) */
  w28 = (- w28 );
  /* #214: (@20[2] += @28) */
  for (rr=w20+2, cs=(&w28); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #215: @28 = 8535 */
  w28 = 8535.;
  /* #216: @24 = fabs(@5) */
  w24 = casadi_fabs( w05 );
  /* #217: @24 = (@28*@24) */
  w24  = (w28*w24);
  /* #218: @7 = 0.000153775 */
  w07 = 1.5377518068583732e-04;
  /* #219: @7 = (@7*@16) */
  w07 *= w16;
  /* #220: @24 = (@24*@7) */
  w24 *= w07;
  /* #221: @24 = (-@24) */
  w24 = (- w24 );
  /* #222: (@20[1] += @24) */
  for (rr=w20+1, cs=(&w24); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #223: @24 = sign(@5) */
  w24 = casadi_sign( w05 );
  /* #224: @5 = (@5*@7) */
  w05 *= w07;
  /* #225: @28 = (@28*@5) */
  w28 *= w05;
  /* #226: @24 = (@24*@28) */
  w24 *= w28;
  /* #227: @24 = (-@24) */
  w24 = (- w24 );
  /* #228: (@20[1] += @24) */
  for (rr=w20+1, cs=(&w24); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #229: @24 = 2829 */
  w24 = 2829.;
  /* #230: @28 = fabs(@3) */
  w28 = casadi_fabs( w03 );
  /* #231: @28 = (@24*@28) */
  w28  = (w24*w28);
  /* #232: @5 = 0.00027027 */
  w05 = 2.7027027027027027e-04;
  /* #233: @5 = (@5*@15) */
  w05 *= w15;
  /* #234: @28 = (@28*@5) */
  w28 *= w05;
  /* #235: @28 = (-@28) */
  w28 = (- w28 );
  /* #236: (@20[0] += @28) */
  for (rr=w20+0, cs=(&w28); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #237: @28 = sign(@3) */
  w28 = casadi_sign( w03 );
  /* #238: @3 = (@3*@5) */
  w03 *= w05;
  /* #239: @24 = (@24*@3) */
  w24 *= w03;
  /* #240: @28 = (@28*@24) */
  w28 *= w24;
  /* #241: @28 = (-@28) */
  w28 = (- w28 );
  /* #242: (@20[0] += @28) */
  for (rr=w20+0, cs=(&w28); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #243: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #244: @10 = @10' */
  /* #245: @13 = mac(@9,@10,@13) */
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w09+j, ct=w10+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #246: @40 = @13' */
  for (i=0, rr=w40, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #247: {@9, @10, @0, @11} = horzsplit(@40) */
  casadi_copy(w40, 4, w09);
  casadi_copy(w40+4, 4, w10);
  casadi_copy(w40+8, 4, w00);
  casadi_copy(w40+12, 4, w11);
  /* #248: @11 = @11' */
  /* #249: {@28, @24, @3, NULL} = horzsplit(@11) */
  w28 = w11[0];
  w24 = w11[1];
  w03 = w11[2];
  /* #250: @3 = (-@3) */
  w03 = (- w03 );
  /* #251: (@20[0] += @3) */
  for (rr=w20+0, cs=(&w03); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #252: (@20[1] += @24) */
  for (rr=w20+1, cs=(&w24); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #253: (@20[2] += @28) */
  for (rr=w20+2, cs=(&w28); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #254: @0 = @0' */
  /* #255: {@28, @24, NULL, @3} = horzsplit(@0) */
  w28 = w00[0];
  w24 = w00[1];
  w03 = w00[3];
  /* #256: (@20[0] += @3) */
  for (rr=w20+0, cs=(&w03); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #257: @24 = (-@24) */
  w24 = (- w24 );
  /* #258: (@20[2] += @24) */
  for (rr=w20+2, cs=(&w24); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #259: (@20[1] += @28) */
  for (rr=w20+1, cs=(&w28); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #260: @10 = @10' */
  /* #261: {@28, NULL, @24, @3} = horzsplit(@10) */
  w28 = w10[0];
  w24 = w10[2];
  w03 = w10[3];
  /* #262: @3 = (-@3) */
  w03 = (- w03 );
  /* #263: (@20[1] += @3) */
  for (rr=w20+1, cs=(&w03); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #264: (@20[2] += @24) */
  for (rr=w20+2, cs=(&w24); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #265: (@20[0] += @28) */
  for (rr=w20+0, cs=(&w28); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #266: @9 = @9' */
  /* #267: {NULL, @28, @24, @3} = horzsplit(@9) */
  w28 = w09[1];
  w24 = w09[2];
  w03 = w09[3];
  /* #268: @3 = (-@3) */
  w03 = (- w03 );
  /* #269: (@20[2] += @3) */
  for (rr=w20+2, cs=(&w03); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #270: @24 = (-@24) */
  w24 = (- w24 );
  /* #271: (@20[1] += @24) */
  for (rr=w20+1, cs=(&w24); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #272: @28 = (-@28) */
  w28 = (- w28 );
  /* #273: (@20[0] += @28) */
  for (rr=w20+0, cs=(&w28); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #274: output[0][2] = @20 */
  if (res[0]) casadi_copy(w20, 3, res[0]+7);
  /* #275: @28 = 7538 */
  w28 = 7538.;
  /* #276: @34 = (@28*@34) */
  w34  = (w28*w34);
  /* #277: output[0][3] = @34 */
  if (res[0]) res[0][10] = w34;
  /* #278: @28 = (@28*@8) */
  w28 *= w08;
  /* #279: output[0][4] = @28 */
  if (res[0]) res[0][11] = w28;
  /* #280: @28 = 9233 */
  w28 = 9233.;
  /* #281: @28 = (@28*@6) */
  w28 *= w06;
  /* #282: output[0][5] = @28 */
  if (res[0]) res[0][12] = w28;
  /* #283: @28 = 8529 */
  w28 = 8529.;
  /* #284: @5 = (@28*@5) */
  w05  = (w28*w05);
  /* #285: output[0][6] = @5 */
  if (res[0]) res[0][13] = w05;
  /* #286: @28 = (@28*@7) */
  w28 *= w07;
  /* #287: output[0][7] = @28 */
  if (res[0]) res[0][14] = w28;
  /* #288: @28 = 11728 */
  w28 = 11728.;
  /* #289: @28 = (@28*@26) */
  w28 *= w26;
  /* #290: output[0][8] = @28 */
  if (res[0]) res[0][15] = w28;
  return 0;
}

CASADI_SYMBOL_EXPORT int standard_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int standard_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int standard_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void standard_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int standard_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void standard_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void standard_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void standard_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int standard_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int standard_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real standard_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* standard_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* standard_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* standard_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* standard_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int standard_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 130;
  return 0;
}

CASADI_SYMBOL_EXPORT int standard_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 130*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
