/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) standard_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* standard_expl_ode_fun:(i0[13],i1[6],i2[0])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, w01, *w02=w+8, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, *w16=w+25, *w17=w+28, *w18=w+31, *w19=w+34, *w20=w+43, *w21=w+52, *w22=w+56;
  casadi_real *w23=w+60, *w24=w+64, *w25=w+68, *w26=w+72, *w27=w+88;
  const casadi_real *cs, *ct;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #1: @1 = 1 */
  w01 = 1.;
  /* #2: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w02);
  /* #3: @3 = @2[2] */
  for (rr=(&w03), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #4: @4 = sq(@3) */
  w04 = casadi_sq( w03 );
  /* #5: @5 = @2[3] */
  for (rr=(&w05), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #6: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #7: @7 = (@4+@6) */
  w07  = (w04+w06);
  /* #8: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #9: @7 = (@1-@7) */
  w07  = (w01-w07);
  /* #10: @8 = @2[1] */
  for (rr=(&w08), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #11: @9 = (@8*@3) */
  w09  = (w08*w03);
  /* #12: @10 = @2[0] */
  for (rr=(&w10), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #13: @11 = (@10*@5) */
  w11  = (w10*w05);
  /* #14: @12 = (@9-@11) */
  w12  = (w09-w11);
  /* #15: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #16: @13 = (@8*@5) */
  w13  = (w08*w05);
  /* #17: @14 = (@10*@3) */
  w14  = (w10*w03);
  /* #18: @15 = (@13+@14) */
  w15  = (w13+w14);
  /* #19: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #20: @16 = horzcat(@7, @12, @15) */
  rr=w16;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w15;
  /* #21: @16 = @16' */
  /* #22: @9 = (@9+@11) */
  w09 += w11;
  /* #23: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #24: @11 = sq(@8) */
  w11 = casadi_sq( w08 );
  /* #25: @6 = (@11+@6) */
  w06  = (w11+w06);
  /* #26: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #27: @6 = (@1-@6) */
  w06  = (w01-w06);
  /* #28: @3 = (@3*@5) */
  w03 *= w05;
  /* #29: @10 = (@10*@8) */
  w10 *= w08;
  /* #30: @8 = (@3-@10) */
  w08  = (w03-w10);
  /* #31: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #32: @17 = horzcat(@9, @6, @8) */
  rr=w17;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w08;
  /* #33: @17 = @17' */
  /* #34: @13 = (@13-@14) */
  w13 -= w14;
  /* #35: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #36: @3 = (@3+@10) */
  w03 += w10;
  /* #37: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #38: @11 = (@11+@4) */
  w11 += w04;
  /* #39: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #40: @1 = (@1-@11) */
  w01 -= w11;
  /* #41: @18 = horzcat(@13, @3, @1) */
  rr=w18;
  *rr++ = w13;
  *rr++ = w03;
  *rr++ = w01;
  /* #42: @18 = @18' */
  /* #43: @19 = horzcat(@16, @17, @18) */
  rr=w19;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #44: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #45: @16 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w16);
  /* #46: @0 = mac(@20,@16,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w20+j, ct=w16+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #47: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #48: @13 = 0.5 */
  w13 = 5.0000000000000000e-01;
  /* #49: @21 = zeros(4x1) */
  casadi_clear(w21, 4);
  /* #50: @3 = 0 */
  w03 = 0.;
  /* #51: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w00);
  /* #52: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #53: @11 = (-@1) */
  w11 = (- w01 );
  /* #54: @4 = @0[1] */
  for (rr=(&w04), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #55: @10 = (-@4) */
  w10 = (- w04 );
  /* #56: @14 = @0[2] */
  for (rr=(&w14), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #57: @9 = (-@14) */
  w09 = (- w14 );
  /* #58: @22 = horzcat(@3, @11, @10, @9) */
  rr=w22;
  *rr++ = w03;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w09;
  /* #59: @22 = @22' */
  /* #60: @23 = horzcat(@1, @3, @14, @10) */
  rr=w23;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w14;
  *rr++ = w10;
  /* #61: @23 = @23' */
  /* #62: @24 = horzcat(@4, @9, @3, @1) */
  rr=w24;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w03;
  *rr++ = w01;
  /* #63: @24 = @24' */
  /* #64: @25 = horzcat(@14, @4, @11, @3) */
  rr=w25;
  *rr++ = w14;
  *rr++ = w04;
  *rr++ = w11;
  *rr++ = w03;
  /* #65: @25 = @25' */
  /* #66: @26 = horzcat(@22, @23, @24, @25) */
  rr=w26;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  /* #67: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #68: @21 = mac(@27,@2,@21) */
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w27+j, ct=w02+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #69: @21 = (@13*@21) */
  for (i=0, rr=w21, cs=w21; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #70: output[0][1] = @21 */
  if (res[0]) casadi_copy(w21, 4, res[0]+3);
  /* #71: @13 = 7538 */
  w13 = 7538.;
  /* #72: @11 = input[1][0] */
  w11 = arg[1] ? arg[1][0] : 0;
  /* #73: @11 = (@13*@11) */
  w11  = (w13*w11);
  /* #74: @3 = 2327 */
  w03 = 2327.;
  /* #75: @9 = @16[0] */
  for (rr=(&w09), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #76: @10 = fabs(@9) */
  w10 = casadi_fabs( w09 );
  /* #77: @3 = (@3*@10) */
  w03 *= w10;
  /* #78: @3 = (@3*@9) */
  w03 *= w09;
  /* #79: @11 = (@11-@3) */
  w11 -= w03;
  /* #80: @3 = 4620 */
  w03 = 4620.;
  /* #81: @11 = (@11/@3) */
  w11 /= w03;
  /* #82: output[0][2] = @11 */
  if (res[0]) res[0][7] = w11;
  /* #83: @11 = input[1][1] */
  w11 = arg[1] ? arg[1][1] : 0;
  /* #84: @13 = (@13*@11) */
  w13 *= w11;
  /* #85: @11 = 4042 */
  w11 = 4042.;
  /* #86: @9 = @16[1] */
  for (rr=(&w09), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #87: @10 = fabs(@9) */
  w10 = casadi_fabs( w09 );
  /* #88: @11 = (@11*@10) */
  w11 *= w10;
  /* #89: @11 = (@11*@9) */
  w11 *= w09;
  /* #90: @13 = (@13-@11) */
  w13 -= w11;
  /* #91: @13 = (@13/@3) */
  w13 /= w03;
  /* #92: output[0][3] = @13 */
  if (res[0]) res[0][8] = w13;
  /* #93: @13 = 9233 */
  w13 = 9233.;
  /* #94: @11 = input[1][2] */
  w11 = arg[1] ? arg[1][2] : 0;
  /* #95: @13 = (@13*@11) */
  w13 *= w11;
  /* #96: @11 = 3135 */
  w11 = 3135.;
  /* #97: @9 = @16[2] */
  for (rr=(&w09), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #98: @10 = fabs(@9) */
  w10 = casadi_fabs( w09 );
  /* #99: @11 = (@11*@10) */
  w11 *= w10;
  /* #100: @11 = (@11*@9) */
  w11 *= w09;
  /* #101: @13 = (@13-@11) */
  w13 -= w11;
  /* #102: @13 = (@13/@3) */
  w13 /= w03;
  /* #103: output[0][4] = @13 */
  if (res[0]) res[0][9] = w13;
  /* #104: @13 = 8529 */
  w13 = 8529.;
  /* #105: @3 = input[1][3] */
  w03 = arg[1] ? arg[1][3] : 0;
  /* #106: @3 = (@13*@3) */
  w03  = (w13*w03);
  /* #107: @11 = 2829 */
  w11 = 2829.;
  /* #108: @9 = fabs(@1) */
  w09 = casadi_fabs( w01 );
  /* #109: @11 = (@11*@9) */
  w11 *= w09;
  /* #110: @11 = (@11*@1) */
  w11 *= w01;
  /* #111: @3 = (@3-@11) */
  w03 -= w11;
  /* #112: @11 = 3700 */
  w11 = 3700.;
  /* #113: @3 = (@3/@11) */
  w03 /= w11;
  /* #114: output[0][5] = @3 */
  if (res[0]) res[0][10] = w03;
  /* #115: @3 = input[1][4] */
  w03 = arg[1] ? arg[1][4] : 0;
  /* #116: @13 = (@13*@3) */
  w13 *= w03;
  /* #117: @3 = 8535 */
  w03 = 8535.;
  /* #118: @11 = fabs(@4) */
  w11 = casadi_fabs( w04 );
  /* #119: @3 = (@3*@11) */
  w03 *= w11;
  /* #120: @3 = (@3*@4) */
  w03 *= w04;
  /* #121: @13 = (@13-@3) */
  w13 -= w03;
  /* #122: @3 = 6503 */
  w03 = 6503.;
  /* #123: @13 = (@13/@3) */
  w13 /= w03;
  /* #124: output[0][6] = @13 */
  if (res[0]) res[0][11] = w13;
  /* #125: @13 = 11728 */
  w13 = 11728.;
  /* #126: @3 = input[1][5] */
  w03 = arg[1] ? arg[1][5] : 0;
  /* #127: @13 = (@13*@3) */
  w13 *= w03;
  /* #128: @3 = 11000 */
  w03 = 11000.;
  /* #129: @4 = fabs(@14) */
  w04 = casadi_fabs( w14 );
  /* #130: @3 = (@3*@4) */
  w03 *= w04;
  /* #131: @3 = (@3*@14) */
  w03 *= w14;
  /* #132: @13 = (@13-@3) */
  w13 -= w03;
  /* #133: @3 = 5582 */
  w03 = 5582.;
  /* #134: @13 = (@13/@3) */
  w13 /= w03;
  /* #135: output[0][7] = @13 */
  if (res[0]) res[0][12] = w13;
  return 0;
}

CASADI_SYMBOL_EXPORT int standard_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int standard_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int standard_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void standard_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int standard_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void standard_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void standard_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void standard_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int standard_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int standard_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real standard_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* standard_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* standard_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* standard_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* standard_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int standard_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 104;
  return 0;
}

CASADI_SYMBOL_EXPORT int standard_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 104*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
