mpc_indi_node:
  ros__parameters:  
    # Model
    motor_max: [3.5] 
    mass: [35.65]
    inertia: [1.19, 1.03, 0.61]
    add_mass: [7.8, 36.8, 36.8, 0.0, 2.3, 2.3]   
    quadratic_damp: [5.1, 36.7, 36.7, 0.0, 1.7, 8.8]
    max_force_moment: [158.4276, 158.4276, 158.4276, 54.6344, 59.6087, 57.6819]
    # todo
    max_vel: [2.0, 2.0, 2.0]
    
    # MPC
    control_freq: 20
    t_horizon: 0.5
    n_nodes: 5
    exp_type: real
